# Change these first
owner: cloudhospitaldev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ClientPlatform
    url: https://icloudhospital.com/api/healthz
    maxResponseTime: 3000 # 3 sec
  - name: AdminPlatform
    url: https://global.icloudhospital.com/api/healthz
    maxResponseTime: 5000 # 3 sec
  - name: ClientApi
    url: https://api.icloudhospital.com/healthz
    maxResponseTime: 3000 # 3 sec
  - name: AdminApi
    url: https://admin-api.icloudhospital.com/healthz
    maxResponseTime: 5000 # 3 sec

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.icloudhospital.com
  # baseUrl: /upptime
  logoUrl: https://chblob.icloudhospital.com/nextjs-ch/icons/logo.png
  name: CloudHospital status
  introTitle: Monitor server status on the CloudHospital platform.
  introMessage: Server status data can be obtained from [cloudhospitaldev/upptime](https://github.com/cloudhospitaldev/upptime).
  navbar:
    - title: Status
      href: /
    - title: CloudHospital
      href: https://icloudhospital.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

skipDeleteIssues: true
